version: '3'


services:
  python_app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:8080"

services:
   nginx:
      image: nginx
      volumes:
         - ./nginx:/etc/nginx/conf.d
         - ./front-end:/var/www/front-end
      ports:
         - "80:80"


