version: '3'


services:
  app:
    build: .
    volumes:
      - .:/app

  nginx:
    image: nginx:latest
    ports:
      - "80:80"

    depends_on:
      - glassfish
    networks:
      - mynetwork

networks:
  mynetwork: