version: '3'


services:
  python_app:
    build:
      ports:
        - "5000:8080"

      networks:
      - mynetwork

services:
   nginx:
      image: nginx

      ports:
         - "80:80"
      networks:
      - mynetwork

networks:
  mynetwork:


